name: t360_frontend_v2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  device_preview: ^1.2.0
  excel: ^2.0.5
  file_picker: ^8.1.2
  fl_chart: ^0.68.0
  fluentui_system_icons: ^1.1.249
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  universal_html: ^2.2.4

icons_launcher:
  image_path: 'lib/assets/logo_motif.png'
  adaptive_icon_background: '#414141'
  platforms:
    android:
      enable: true
    ios:
      enable: true
    web:
      enable: true
      image_path: 'lib/assets/logo_motif.png'
      favicon_path: 'lib/assets/logo_motif.png'
    macos:
      enable: false
    windows:
      enable: false
    linux:
      enable: false

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
